image: docker:git
services:
- docker:dind

build_fedora:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/mono:f24 ./fedora
    - docker push registry.gitlab.com/gbraad/mono:f24

build_centos:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/mono:c7 ./centos
    - docker push registry.gitlab.com/gbraad/mono:c7
